#!/usr/bin/env python3
"""Fold every lean per-case record into the Supply Code jurisprudence spine.

Usage:  python tools/build_supply_code.py
Reads  supply-code/summaries/json/*.json
Writes supply-code/jurisprudence/index.json

The spine is keyed two ways:
  - by provision (holding_units[].provision, e.g. "UP-2005::4.3(f)") -> every case
    construing that clause, each with its holding + pins + treatment/flags;
  - by principle (principle_tags[].tag) -> the cross-cutting doctrines.
Plus a not-decided register and a flat case list. Deterministic: safe to re-run
after each batch. No hand-editing of index.json.
"""
import json, glob, os

ROOT = os.path.join(os.path.dirname(__file__), "..", "supply-code")
SUMM = os.path.join(ROOT, "summaries", "json")
OUT = os.path.join(ROOT, "jurisprudence", "index.json")


def load_cases():
    cases = []
    for path in sorted(glob.glob(os.path.join(SUMM, "*.json"))):
        with open(path) as f:
            cases.append(json.load(f))
    return cases


def build(cases):
    provisions = {}
    principles = {}
    not_decided = []
    case_list = []

    for c in cases:
        cid = c.get("case_id")
        ident = {
            "case_id": cid,
            "title": c.get("title", ""),
            "neutral_citation": c.get("neutral_citation", ""),
            "court": c.get("court", ""),
            "date": c.get("date_display") or c.get("date_of_judgment", ""),
        }
        case_list.append({**ident, "disposition": c.get("disposition", ""),
                          "holding_units": len(c.get("holding_units", []))})

        for hu in c.get("holding_units", []):
            key = hu.get("provision") or hu.get("clause") or "UNKEYED"
            p = provisions.setdefault(key, {
                "code": hu.get("code", ""),
                "clause": hu.get("clause", ""),
                "topic": hu.get("topic", ""),
                "cases": [],
            })
            entry = {
                **ident,
                "type": hu.get("type", "supply_code"),
                "topic": hu.get("topic", ""),
                "holding": hu.get("holding", ""),
                "paras": hu.get("paras", ""),
            }
            if hu.get("flag"):
                entry["flag"] = hu["flag"]
            p["cases"].append(entry)

        for t in c.get("principle_tags", []):
            pr = principles.setdefault(t.get("tag", "UNTAGGED"), {"cases": []})
            pr["cases"].append({
                **ident,
                "application": t.get("application", ""),
                "lead_authorities": t.get("lead_authorities", []),
                "paras": t.get("paras", ""),
            })

        for nd in c.get("not_decided", []):
            not_decided.append({**ident, "point": nd.get("point", ""),
                                "note": nd.get("note", "")})

    # stable ordering
    provisions = dict(sorted(provisions.items()))
    principles = dict(sorted(principles.items()))

    return {
        "project": "Supply Code Jurisprudence",
        "description": "Cross-case spine, generated by tools/build_supply_code.py from the "
                       "lean per-case records in summaries/json/. Keyed by Supply Code "
                       "provision and by legal principle. Do not hand-edit.",
        "keyed_by": "supply_code_provision + principle",
        "case_count": len(cases),
        "provision_count": len(provisions),
        "cases": case_list,
        "provisions": provisions,
        "principles": principles,
        "not_decided_register": not_decided,
    }


if __name__ == "__main__":
    cases = load_cases()
    index = build(cases)
    with open(OUT, "w") as f:
        json.dump(index, f, ensure_ascii=False, indent=2)
    print(f"wrote {OUT}: {index['case_count']} cases, "
          f"{index['provision_count']} provisions, "
          f"{len(index['principles'])} principles, "
          f"{len(index['not_decided_register'])} not-decided entries")
