#!/usr/bin/env python3
"""Fold every lean per-case record into the Supply Code jurisprudence spine.

Usage:  python tools/build_supply_code.py
Reads  supply-code/summaries/json/*.json
Writes supply-code/jurisprudence/index.json

The spine is keyed two ways:
  - by provision (holding_units[].provision, e.g. "UP-2005::4.3(f)") -> every case
    construing that clause, each with its holding + pins + treatment/flags;
  - by principle (principle_tags[].tag) -> the cross-cutting doctrines.
Plus a not-decided register and a flat case list. Deterministic: safe to re-run
after each batch. No hand-editing of index.json.
"""
import json, glob, os

ROOT = os.path.join(os.path.dirname(__file__), "..", "supply-code")
SUMM = os.path.join(ROOT, "summaries", "json")
OUT = os.path.join(ROOT, "jurisprudence", "index.json")


def load_cases():
    cases = []
    for path in sorted(glob.glob(os.path.join(SUMM, "*.json"))):
        # encoding=utf-8 is required on Windows: locale open() is cp1252 and
        # dies on curly quotes (U+201D -> byte 0x9d) in the older records.
        with open(path, encoding="utf-8") as f:
            cases.append(json.load(f))
    return cases


def build(cases):
    provisions = {}
    principles = {}
    not_decided = []
    case_list = []
    authorities = {}

    for c in cases:
        cid = c.get("case_id")
        ident = {
            "case_id": cid,
            "title": c.get("title", ""),
            "neutral_citation": c.get("neutral_citation", ""),
            "court": c.get("court", ""),
            "date": c.get("date_display") or c.get("date_of_judgment", ""),
        }
        row = {**ident, "disposition": c.get("disposition", ""),
               "holding_units": len(c.get("holding_units", []))}
        if isinstance(c.get("page_count"), int) and c["page_count"] > 0:
            row["page_count"] = c["page_count"]
        if c.get("significance"):
            row["significance"] = c["significance"]
        if c.get("outcome"):
            row["outcome"] = c["outcome"]
        case_list.append(row)

        for hu in c.get("holding_units", []):
            key = hu.get("provision") or hu.get("clause") or "UNKEYED"
            p = provisions.setdefault(key, {
                "code": hu.get("code", ""),
                "clause": hu.get("clause", ""),
                "topic": hu.get("topic", ""),
                "cases": [],
            })
            entry = {
                **ident,
                "type": hu.get("type", "supply_code"),
                "topic": hu.get("topic", ""),
                "holding": hu.get("holding", ""),
                "paras": hu.get("paras", ""),
            }
            if c.get("outcome"):
                entry["outcome"] = c["outcome"]
            if hu.get("flag"):
                entry["flag"] = hu["flag"]
            p["cases"].append(entry)

        for t in c.get("principle_tags", []):
            pr = principles.setdefault(t.get("tag", "UNTAGGED"), {"cases": []})
            pr["cases"].append({
                **ident,
                "application": t.get("application", ""),
                "lead_authorities": t.get("lead_authorities", []),
                "paras": t.get("paras", ""),
            })

        for nd in c.get("not_decided", []):
            not_decided.append({**ident, "point": nd.get("point", ""),
                                "note": nd.get("note", "")})

        # cross-case table of authorities — every citation, electricity-related or not
        for a in c.get("authorities", []):
            key = a.get("docid") or a.get("name", "")
            led = authorities.setdefault(key, {
                "name": a.get("name", ""),
                "citation": a.get("citation", ""),
                "court": a.get("court", ""),
                "docid": a.get("docid", ""),
                "proposition": a.get("proposition", ""),
                "cited_in": [],
            })
            led["cited_in"].append({
                "case_id": cid,
                "title": c.get("title", ""),
                "cited_by": a.get("cited_by", ""),
                "treatment": a.get("treatment", ""),
                "how_treated": a.get("how_treated", ""),
                "paras": a.get("how_treated_paras", ""),
            })

    # stable ordering
    provisions = dict(sorted(provisions.items()))
    principles = dict(sorted(principles.items()))
    authorities = dict(sorted(authorities.items(), key=lambda kv: kv[1]["name"].lower()))

    return {
        "project": "Supply Code Jurisprudence",
        "description": "Cross-case spine, generated by tools/build_supply_code.py from the "
                       "lean per-case records in summaries/json/. Keyed by Supply Code "
                       "provision and by legal principle. Do not hand-edit.",
        "keyed_by": "supply_code_provision + principle",
        "case_count": len(cases),
        "provision_count": len(provisions),
        "authority_count": len(authorities),
        "cases": case_list,
        "provisions": provisions,
        "principles": principles,
        "authorities_ledger": authorities,
        "not_decided_register": not_decided,
    }


if __name__ == "__main__":
    cases = load_cases()
    index = build(cases)
    with open(OUT, "w", encoding="utf-8") as f:
        json.dump(index, f, ensure_ascii=False, indent=2)
    print(f"wrote {OUT}: {index['case_count']} cases, "
          f"{index['provision_count']} provisions, "
          f"{len(index['principles'])} principles, "
          f"{index['authority_count']} authorities, "
          f"{len(index['not_decided_register'])} not-decided entries")
